https://docs.python.org/3/tutorial/modules.html#the-module-search-path
https://stackoverflow.com/questions/6393861/how-python-deals-with-module-and-package-having-the-same-nam
---------------------------------------------------------------------------

Python will check your working directory for module imports first.  If you work from an IDE or text editor, be mindful that hard to diagnose errors can 
arise from having the same name as a module (and many mondules can, at times, be imported)

What can I say, I used some very original names going through the tutorials, like: numpy.py, matplotlib.py and keras.py for my working file. ;)

In the error message, check if one of the 'strings' is the same as the name of a '.py' file in your working directory.  It's not a bug, it's a feature. 
Try changing the name (e.g. add '1234' to the end before .py)

Possible Related Errors: ModuleNotFoundError, ImportError, AttributeError
----------------------------------------------------------------------------

*Note:  Some of these modules may not yet be installed on your system.  (e.g. keras-tuner)

Module Search Path, Command Line Illustration::

username@usernameubuntu:~$ mkdir import_paths && cd import_paths
username@usernameubuntu:~/import_paths$ ls
username@usernameubuntu:~/import_paths$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import inspect
>>> inspect.getfile(tf)
'/usr/local/lib/python3.9/dist-packages/tensorflow/__init__.py'
>>> exit()

username@usernameubuntu:~/import_paths$ touch tensorflow.py
username@usernameubuntu:~/import_paths$ ls
tensorflow.py
username@usernameubuntu:~/import_paths$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import inspect
>>> inspect.getfile(tf)
'/home/username/import_paths/tensorflow.py'
>>> from tensorflow import keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'keras' from 'tensorflow' (/home/username/import_paths/tensorflow.py)
>>> exit()

username@usernameubuntu:~/import_paths$ ls
__pycache__  tensorflow.py
username@usernameubuntu:~/import_paths$ rm -rf __pycache__/ tensorflow.py
username@usernameubuntu:~/import_paths$ touch inspect.py
username@usernameubuntu:~/import_paths$ ls
impinspect.py
username@usernameubuntu:~/import_paths$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/eager/context.py", line 26, in <module>
    import numpy as np
  File "/home/username/.local/lib/python3.9/site-packages/numpy/__init__.py", line 157, in <module>
    from . import ma
  File "/home/username/.local/lib/python3.9/site-packages/numpy/ma/__init__.py", line 42, in <module>
    from . import core
  File "/home/username/.local/lib/python3.9/site-packages/numpy/ma/core.py", line 7646, in <module>
    inner.__doc__ = doc_note(np.inner.__doc__,
  File "/home/username/.local/lib/python3.9/site-packages/numpy/ma/core.py", line 124, in doc_note
    notesplit = re.split(r'\n\s*?Notes\n\s*?-----', inspect.cleandoc(initialdoc))
AttributeError: module 'inspect' has no attribute 'cleandoc'
>>> exit()

username@usernameubuntu:~/import_paths$ rm -rf __pycache__/ inspect.py
username@usernameubuntu:~/import_paths$ touch keras.py
username@usernameubuntu:~/import_paths$ ls
keras.py
username@usernameubuntu:~/import_paths$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import inspect
>>> inspect.getfile(tf)
'/usr/local/lib/python3.9/dist-packages/tensorflow/__init__.py'
>>> inspect.getfile(inspect)
'/usr/lib/python3.9/inspect.py'
>>> from tensorflow import keras
>>> inspect.getfile(keras)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/inspect.py", line 658, in getfile
    if getattr(object, '__file__', None):
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/util/lazy_loader.py", line 58, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keras.api'; 'keras' is not a package
>>> import keras_tuner as kt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/keras_tuner/__init__.py", line 16, in <module>
    from keras_tuner import applications
  File "/usr/local/lib/python3.9/dist-packages/keras_tuner/applications/__init__.py", line 16, in <module>
    from keras_tuner.applications.augment import HyperImageAugment
  File "/usr/local/lib/python3.9/dist-packages/keras_tuner/applications/augment.py", line 17, in <module>
    import tensorflow.keras as keras
ModuleNotFoundError: No module named 'tensorflow.keras'
>>> exit()

username@usernameubuntu:~/import_paths$ ls
keras.py  __pycache__
username@usernameubuntu:~/import_paths$ rm -rf __pycache__/ keras.py
username@usernameubuntu:~/import_paths$ ls
username@usernameubuntu:~/import_paths$ python3
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import inspect
>>> from tensorflow import keras
>>> inspect.getfile(keras)
'/usr/local/lib/python3.9/dist-packages/keras/api/_v2/keras/__init__.py'
>>> exit()
username@usernameubuntu:~/import_paths$ cd ../ && rm -rf import_paths/
username@usernameubuntu:~$ 
